## Write a Numpy program to compute the multiplication of two given matrixes

In [3]:
import numpy as np
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]
x=np.array(my_matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Write a NumPy program to compute the determinant of a given square array

In [9]:
a = np.array([[1, 0], [1, 2]])
print(np.linalg.det(a))

2.0


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
x=[[4,5,6],[7,8,9]]
y=[[1,2,3],[7,5,2]]
np.cross()

array([[  3,  -6,   3],
       [-29,  49, -21]])

## Write a NumPy program to compute the condition number of a given matrix

In [11]:
np.linalg.cond(a)

2.618033988749896

## Write a NumPy program to compute the inverse of a given matrix

In [12]:
np.linalg.inv(a)

array([[ 1. ,  0. ],
       [-0.5,  0.5]])